services:
  - type: web
    name: cyber-cafe-management-system
    env: node
    plan: free
    region: oregon
    buildCommand: npm --prefix backend install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
